services:
  gcloud:
    build: .
    container_name: gcloud-dev
    tty: true
    stdin_open: true
    environment:
      - CLOUDSDK_CONFIG=/gcloud
      - GOOGLE_APPLICATION_CREDENTIALS=/gcloud/application_default_credentials.json
    volumes:
      - gcloud-config:/gcloud
      - ./:/app
volumes:
  gcloud-config:
